Update from Netty to Jetty
deephaven-examples/redpanda-dxfeed-financial-data pull request #4
Opened 2022-10-27 17:23 UTC by jjbrosnan

The setup in main is broken. It uses the Netty docker setup, which no longer works. This fixes it, and runs with the capabilities as expected.

2022-10-27 20:54 UTC, devinrsmith requested changes

2022-10-27 20:54 UTC, devinrsmith commented on Dockerfile
> +HEALTHCHECK --interval=3s --retries=3 --timeout=11s CMD /bin/grpc_health_probe -addr=localhost:8080 -connect-timeout=10s || exit 1
The healthcheck should be part of the jetty image, so we shouldn't need it here - and it would be port 10000 instead of 8080...

2022-10-27 20:54 UTC, devinrsmith commented on docker-compose.yml
> +      - JAVA_OPTS=-Xmx12g -Ddeephaven.application.dir=/data/app.d
We'll be updating other documents soon, but we should migrate to using `START_OPTS` in the majority of our examples instead of `JAVA_OPTS`.

2022-10-28 19:09 UTC, chipkent reviewed
Approved pending Devin's changes.

2022-10-28 20:36 UTC, merged